### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by kendrickkay** [nrdg/fracridge#11]
Can we improve fracridge's documentation, to make it more user friendly ?

In particular, perhaps we need an example that shows how multipel targets can be handled?    in particular, plot_diabetes.html shows an example of just one target?   maybe we need an example of multiple targets and how the user can do n-fold cross-validation or something??  

For that matter, the MATLAB side of things probably needs more examples too... hmm...

We currently have this: https://nrdg.github.io/fracridge/
But shouldn't we have something that looks like: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge  ?

The docstrings seem more informative than what is available through the web, so maybe we should propagate ?

**Comment by arokem** [comment]
This is addressed in #12
