### ISSUE TITLE
missing imports and string error

### ISSUE THREAD

**Issue by hahahannes** [nrdg/fracridge#33]
Hi :)

I experienced two small errors. The first one is that an import of `lapack` is missing (https://github.com/nrdg/fracridge/blob/master/fracridge/_linalg.py#L102) and the second one is that the splitting of the too long line (https://github.com/nrdg/fracridge/blob/master/fracridge/fracridge.py#L39) throws an error.

**Comment by arokem** [comment]
Thanks for reporting! What code are you running that raises the string-splitting error that you mentioned? And in what environment? OS, Python version, etc.
