### ISSUE TITLE
scikit-learn version

### ISSUE THREAD

**Issue by hahahannes** [nrdg/fracridge#37]
Hi :)
I was just wondering, if there is specific reason why the scikit-learn version is fixed on 0.23 and not the current 1.0?

**Comment by arokem** [comment]
Yeah. See issues that arose in https://github.com/nrdg/fracridge/pull/31. Have not managed to resolve those yet, but haven't taken a close look in a while. I will try pushing there, to give the CI a chance to install 1.0

**Comment by hahahannes** [comment]
Thanks for the fast reply and sorry for not checking the PR. Should have seen it before submitting the issue.
And thanks for having a look!
