### ISSUE TITLE
np.squeeze of the regression coefficients breaks glmsingle

### ISSUE THREAD

**Issue by Tal-Golan** [nrdg/fracridge#39]
We encountered an error in the Python version of GLMsingle when analyzing a particular dataset. It turns out that the error was caused by the output of `fracridge.py`. The following line squeezes the resulting coefficient array:
https://github.com/nrdg/fracridge/blob/1ac49cae092cca3efa083451808c26989d17a3b5/fracridge/fracridge.py#L210 

There was an edge condition for our fMRI data where the following line 
https://github.com/cvnlab/GLMsingle/blob/c9326eefb57a74d49050b2330fd7267b979bc06b/glmsingle/ols/glm_estimatemodel.py#L561
called `fracridge` with a scalar `fracs` (a single ridge penalty) and a `data2` array with the shape (1,629) (a single voxel x 629 timepoints). The `np.squeeze` call reduced the coefficient array from a 1 x 629 matrix to a 629-long vector, which is not what glmsingle was expecting, hence throwing an error later.

The following line in glmsingle was assuming that the betas array is either 2D or 3D, where in fact it was 1D:
https://github.com/cvnlab/GLMsingle/blob/d88744be194fdae701764494c663c26e13b5a5ec/glmsingle/ols/glm_estimatemodel.py#L728

In general, I think that a squeeze operation is unsafe in this context - the user might run a script in which `pp`, `ff` or `bb` are _sometimes_ 1. The dimensions of the coefficient matrix shouldn't change as a function of this condition.

The only case in which an np.squeeze call might be safe is when  `fracs` is scalar (not a single element vector). Then the second dimension can be specifically squeezed by `coef.squeeze(1)`.

EDIT: in the pull request below, I introduced a conditional squeeze of both the target and fracs dimensions that does not include the problematic singleton fracs or targets cases.

**Comment by arokem** [comment]
Honestly, I am not following the full story here. I understand that one value of frac was provided, but what were the shapes of y and X that were provided?

**Comment by Tal-Golan** [comment]
X had the shape (629, 64) (629 timepoints x 64 conditions) and y had the shape (629,1) (629 timepoints and one voxel). IMHO, the resulting coefficient matrix should have the shape (64,1), not (64,) as it is right now.

**Comment by kendrickkay** [comment]
Just to chime in, yes it would be best if the implementation were general.  Assuming that python's squeeze is like MATLAB's squeeze, then, yeah, in MATLAB world, I in general always deliberately avoid using squeeze and instead explicitly use permute/reshape, etc., for maximum generality and precision.

**Comment by arokem** [comment]
Can we close this now that #40 is merged?
